### PR TITLE
Fixed mismatched sections in i. Abstract

### PR DESCRIPTION
**Pull request by jerstlouis**

### CODE REVIEW

**Comment by bpross-52n** [comment]
Thanks Jerome, let me know if this is ready to merge or if you want to add something or are waiting for discussion. (Not necessary in this case, IMHO)

**Comment by pvretano** [comment]
@bpross-52n @jerstlouis don't merge this yet.  There is a general requirement to figure out the wording ... What I mean by that is that throughout the document we use the wording "create a job" when we mean "execute a process".  I believe that the later wording is more intuitive and I have a PR that makes that shift plus makes a bunch of other editorial changes.  If you both agree with the shift from "create a job" to "execute a process" than I'll push my PR to the repo and merge this PR and mine.  There will likely be merge conflicts between the two that will need to be resolved.

**Comment by jerstlouis** [comment]
@bpross-52n Yes it's ready to merge, this is just aligning the references to the sections to use the actual headers of the section. But since @pvretano has a potentially conflicting PR best to let him do it.

I agree with the _Create a job_ -> _Execute a process change_, the change was already there in the title of section 7.9 (though not in the anchor (https://docs.ogc.org/DRAFTS/18-062.html#sc_create_job) I realize). This PR just changed references to sections to use matching titles.

**Comment by pvretano** [comment]
@bpross-52n @jerstlouis I'll merge this one now and resolve and conflict through the other PR.  It will be a few days before I finish that on and am able to merge.

**Comment by gfenoy** [comment]
@pvretano in case I can of any help in anything, please feel free to inform me.

**Pull request merged**
