### PR TITLE
Changes to get Metanorma to build locally.

### PR DESCRIPTION
**Pull request by gbuehler**
I am finding all kinds of silly ways to break Metanorma.

So far, I have had to

1) Take single quotes from table titles (replaced with backticks) as they put extraneous text in the HTML file. [NOTE:  This is only an issue in the front material.]

Screenshot 2023-09-12 at 5.07.06 PM.png

In clause_0_front_material.adoc, this works:

----
[[table_core_resources]]
.Requirements class `Core`
[cols="27,25,10,10,28",options="header"]
----

This does not:

----
[[table_core_resources]]
.Requirements class 'Core'
[cols="27,25,10,10,28",options="header"]
----

However, in clause_9_security-considerations.adoc, this works:

----
[[table_core_safe_operations_security]]
.Requirements class 'Core' - Overview of core operations and returned sensitive information
[cols="20,30,10,40",options="header"]
----

2) In an included requirement (REQ_test-process.adoc), a cross-reference to a future included item's (REC_test-process.adoc) bookmark doesn't seem to work.

In REQ_test-process.adoc, this works:

----
If a server implementing the OGC API - Processes - Part 1: Core is tested using CITE tests, the server SHALL offer at least one testable process. Please refer to  
// <<rec_core_test-process>>
 for further guidance.

----

This does not:

----
If a server implementing the OGC API - Processes - Part 1: Core is tested using CITE tests, the server SHALL offer at least one testable process. Please refer to   <<rec_core_test-process>> for further guidance.
----

NOTE:  I have not figured out how to actually fix this yet!

3) It seems that explicit ordering of ordered lists with subitems (nested) in Abstract Test items does not work

In ATS_landingpage-success.adoc, this works:

----
test-method::
+
--

. Validate that a document was returned with an HTTP status code or 200.

. Validate the landing page for all supported media types using the resources and tests identified in <<landing-page-schema>>

. For formats that require manual inspection, perform the following:

.. Validate that the landing page includes a "service-desc" and/or "service-doc" link to an API Definition.

.. Validate that the landing page includes a "http://www.opengis.net/def/rel/ogc/1.0/conformance" link to the conformance class declaration.

.. Validate that the landing page includes a "http://www.opengis.net/def/rel/ogc/1.0/processes" link to the list of processes.

--
----

This does not:

----
+
--

1. Validate that a document was returned with an HTTP status code or 200.

2. Validate the landing page for all supported media types using the resources and tests identified in <<landing-page-schema>>

3. For formats that require manual inspection, perform the following:

    a. Validate that the landing page includes a "service-desc" and/or "service-doc" link to an API Definition.

    b. Validate that the landing page includes a "http://www.opengis.net/def/rel/ogc/1.0/conformance" link to the conformance class declaration.

    c. Validate that the landing page includes a "http://www.opengis.net/def/rel/ogc/1.0/processes" link to the list of processes.

--
----

4) This didn't stop the build, but it was displaying incorrectly:

Screenshot 2023-09-12 at 5.26.45 PM.png

This does not work:

----
[[ats_ogc-process-description]][conformance_class]
----

This works:

----
 [[ats_ogc-process-description]]

[conformance_class]
----

### CODE REVIEW

**Comment by jerstlouis** [comment]
Thanks a lot @gbuehler for doing all the hard work of debugging this.

Of the issues you mentioned seemed like a similar issue to what we faced in DGGS trying to include code blocks inside requirement parts ( https://github.com/metanorma/metanorma/issues/312 ).

Could you / we please edit this commit to avoid adding the generated PDF / HTML to the repository?

We should probably also add this to a _.gitignore_ to avoid this from accidentally happening in the future.
I think *.pdf should perhaps even be in the default _.gitignore_ of all default OGC templates :)

**Comment by jerstlouis** [comment]
Merging this as-is added the generated PDF into the repository, forever increasing the size of the repository by 5 Megabytes :(

**Comment by pvretano** [comment]
Doh!  @jerstlouis forgot about it even though @gbuehler menitoned it in his email.  I'll just remove the PDF and HTML.  The entire point of the thread was to auto generate these anyway.  OK?

**Comment by jerstlouis** [comment]
@pvretano Ideally you would do this with a `git commit --amend` followed by a `git push --force` as opposed to a new commit, so as to delete it from the history.

**Comment by pvretano** [comment]
@jerstlouis can you do it?  I might screw it up because I have never had to amend a merge commit.

**Comment by jerstlouis** [comment]
@pvretano Sure, I will do it but it means that everyone should then:

- git stash any unstaged (not added / not committed) local work area changes
- git fetch
- git reset --hard origin/master
- git stash pop (if any stashed changes to restore)

Otherwise someone might re-introduce the commit again by merging with the older version.

I passionately hate merge commits about as much as I hate generated PDFs in Git repositories :)

**Comment by jerstlouis** [comment]
@pvretano  Done.

**Pull request merged**
