### PR TITLE
BBOX, Example server #1, README

### PR DESCRIPTION
**Pull request by jerstlouis**

### CODE REVIEW

**Comment by jerstlouis** [comment]
Merged.

**Comment by fmigneault** [comment]
Just curious. 
What's the point of the `anyOf` if the enum is short-circuited with the generic string URI format?
Can't the definition be simplified only to that URI format, and move the enum values to `examples`?

**Comment by pvretano** [comment]
@fmigneault normally that enum list would be augmented with the list of CRSs that the server actually supports.  However, should anyone extent the list and they try validation using the schemas at opengis.net, validation will fail.  The short circuit is to allow validation again the normative schemas at opengis.net to succeed when the server supports more than just CRS84 and CRS84h.  @jerstlouis can probably explain it better than me.

**Comment by jerstlouis** [comment]
@fmigneault We discussed this in the call this morning. There is a permission that says that implementations can add additional values to the "enum" to declare the CRSs that they support from the OpenAPI definition.
At the moment, there is no other way to do so.

I added an additional note that clarifies that the reason for the `anyOf` is so that execution requests will validate against the OGC canonical schema.

**Pull request closed without merging**
