### PR TITLE
Issue 221

### PR DESCRIPTION
**Pull request by gfenoy**
it should solve the issue #221 

As the server may not implement the dismiss conformance class, I guess there is no need to add the `"dismiss"` item in the `jobControlOption` array.

### CODE REVIEW

**Comment by jerstlouis** [comment]
@pvretano @gfenoy 

I'm not sure it is correct to have a "default" in _jobControlOptions.yaml_.

This particular schema only appears in the process description's list of available _jobControlOptions_ as an array, where there really is no default -- every supported control option must be explicitly listed.

There also isn't really a default execution mode (and this is more than about execution mode too -- dismiss is not an execution mode).
Sync execution is only default if the server does advertise `sync-execute` and no _Prefer:_ header is used.

**Comment by pvretano** [comment]
@jerstlouis that was already there so we should NOT mix issues this way.  Create a NEW issue for the default value of `jobControlOptions` and I will create a new PR to fix that.
@gfenoy Please undo the change that changes `process-desc` to `self`.  Again, you are mixing issues and this will cause a merge conflict with the other PR (#220) which was, in fact, about changing `process-desc` to `self`.

**Comment by jerstlouis** [comment]
@pvretano Sorry. Here: #224

**Comment by bpross-52n** [comment]
We need to change process-desc to self, I will take care of it.

**Comment by bpross-52n** [comment]
Merged using command line, see 89389d1f5b1c2054684de640f1f73f0c6b4c8bc5

**Pull request closed without merging**
