### PR TITLE
Partially addressing issue #283

### PR DESCRIPTION
**Pull request by jerstlouis**

### CODE REVIEW

**Comment by fmigneault** [comment]
I think it is important to preserve the job creation. While execution is more relevant during `sync`, a job is created with status location in `async`. Job also refers to the `/jobs` endpoints. These definitions are what highlights the connection between processes and jobs endpoints.

**Comment by jerstlouis** [comment]
@fmigneault This is only editorial fixes. Sync execution can still result in job creation if the server wishes so, but they are not required. This PR only fixes the abstract tests to match changes already made to the requirements.

**Comment by fmigneault** [comment]
Not only editorial. It modifies items such as `/req/core/job-creation-op`, which are referred by existing APIs in `conformsTo`. 
These should remain as is. I don't mind about the text and abstract tests portions.

**Comment by jerstlouis** [comment]
@fmigneault That change was done prior to 1.0, just the Abstract Tests had not been updated.

**Comment by fmigneault** [comment]
I disagree, they are already found here: https://docs.ogc.org/is/18-062r2/18-062r2.html
This is approved and published for over half a year.

**Comment by jerstlouis** [comment]
@fmigneault In the abstract test. This is also note what goes in `conformsTo`, the list of conformance classes is in [Table 8](https://docs.ogc.org/is/18-062r2/18-062r2.html#toc9).

**Comment by fmigneault** [comment]
No. I am referring to the requirements themselves. Because there are so many of them, I refer to them individually in the code otherwise I must always navigate across the full spec to find specific items. Conformance classes are not verbose enough in some cases about which specific requirement a part of the code implements or validates.

**Comment by jerstlouis** [comment]
@fmigneault The requirement to execute a process is `/req/core/process-execute-op` in the published 1.0 version that you linked to. `/req/core/job-creation-op` was only used in the Abstract Test and is a broken link because it was not updated.

My PR does change one requirement label from `/req/core/process` to `/req/core/process-description` (or should it be /req/core/process-description-op`?) (Requirement 13 and maybe 14 as well?) to match the requirement file name, but we can discuss whether that change should be made or not.

**Comment by fmigneault** [comment]
Indeed, you are right. Good to go for the change then since links are broken anyway.

Yes, maybe it is better to align the `...-op` name to keep them consistent.

**Review by pvretano — APPROVED** [review]

**Pull request merged**
