### PR TITLE
OGC API 18-062 markup corrections

### PR DESCRIPTION
**Pull request by anermina**
Markup corrections made in accordance to https://github.com/metanorma/ogcapi-processes/issues/9 and https://github.com/metanorma/ogcapi-processes/issues/10.

### CODE REVIEW

**Comment by manuel489** [comment]
@anermina, in regard to the commit: https://github.com/opengeospatial/ogcapi-processes/pull/254/commits/bc7c6a30df71c68f857cc46c11f8b9ecef7385ce
This was a markup convention agreed with Nick in the comment: https://github.com/metanorma/ogcapi-processes/issues/2#issuecomment-895950329
That's why I encoded it on that way.
Now, to be honest, I find more sense in the way that you edited the abstract test.

**Comment by anermina** [comment]
Thanks for letting me know, @manuel489 !
I will ask Nick for his opinion on this.

**Comment by ronaldtse** [comment]
@anermina can you make the PR to the metanorma fork instead of this one? We have to complete our copy before making a PR here. Thanks.

**Comment by ronaldtse** [comment]
@anermina can you please help close this after vacation? Thanks!

**Pull request closed without merging**
