### PR TITLE
Use inlineOrRefData rather than valueType

### PR DESCRIPTION
**Pull request by gfenoy**
Avoid using inlineValue / reference in outputs as for inputs

### CODE REVIEW

**Comment by bpross-52n** [comment]
Thanks Gérald. We decided on some changes to the schema during the SWG session on Monday, December 7th. I will send around a summary of the changes soon and I will check how this fits in there.

**Comment by gfenoy** [comment]
Thanks a lot for your answer, sorry for missing the meeting.

I would appreciate to know if a decision has been taken about moving to JSON object for input rather than the array currently used. Even in that case, the situation would be the same IMO, meaning that we should consider having the same syntaxe for both input and output (using JSON object).

**Comment by bpross-52n** [comment]
OutputInfo.yaml has been removed. The content moved to [results.yaml](https://github.com/opengeospatial/ogcapi-processes/blob/master/core/openapi/schemas/result.yaml). @gfenoy Please check if the changes of this PR are reflected there now.

**Comment by gfenoy** [comment]
They are reflected, @bpross-52n thanks for the work.

**Pull request closed without merging**
